//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Three_Layered_Website_Plus_Wizards.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Three_Layered_Website_Plus_Wizards.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove the admin role here as the site will need an admin so you can have at least one user..
        /// </summary>
        internal static string AdminRemovalWaringText {
            get {
                return ResourceManager.GetString("AdminRemovalWaringText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete!.
        /// </summary>
        internal static string AdminRemovalWaringTitle {
            get {
                return ResourceManager.GetString("AdminRemovalWaringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        internal static string ConnectionStringSetupForm_Checkbox_Toggle {
            get {
                return ResourceManager.GetString("ConnectionStringSetupForm_Checkbox_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Issues.
        /// </summary>
        internal static string ConnectionStringSetupForm_ConnectionIssues {
            get {
                return ResourceManager.GetString("ConnectionStringSetupForm_ConnectionIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Please report this to the extension publisher..
        /// </summary>
        internal static string ConnectionStringSetupForm_TestConnection_InvalidOperationException {
            get {
                return ResourceManager.GetString("ConnectionStringSetupForm_TestConnection_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Issues.
        /// </summary>
        internal static string ConnectionStringSetupForm_TestConnection_InvalidOperationException_Title {
            get {
                return ResourceManager.GetString("ConnectionStringSetupForm_TestConnection_InvalidOperationException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection was successful.
        /// </summary>
        internal static string ConnectionStringSetupForm_TestConnection_Successful {
            get {
                return ResourceManager.GetString("ConnectionStringSetupForm_TestConnection_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL connection.
        /// </summary>
        internal static string ConnectionStringSetupForm_TestConnection_Successful_Title {
            get {
                return ResourceManager.GetString("ConnectionStringSetupForm_TestConnection_Successful_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected exception.
        /// </summary>
        internal static string ConnectionStringSetupForm_UnexpectedException {
            get {
                return ResourceManager.GetString("ConnectionStringSetupForm_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is already a role in the list.
        ///Do you wish to create a duplicate?.
        /// </summary>
        internal static string DuplicateRoleWarningText {
            get {
                return ResourceManager.GetString("DuplicateRoleWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate role!.
        /// </summary>
        internal static string DuplicateRoleWarningTitle {
            get {
                return ResourceManager.GetString("DuplicateRoleWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string ExceptionCodeMessageSeperator {
            get {
                return ResourceManager.GetString("ExceptionCodeMessageSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unchecked the HTTPS everywhere checkbox, this puts you and your users at risk.
        ///Are you sure you want to create a website without HTTPS turned on?.
        /// </summary>
        internal static string HTTPSUncheckedWarning {
            get {
                return ResourceManager.GetString("HTTPSUncheckedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTPS unchecked!.
        /// </summary>
        internal static string HTTPSUncheckedWarningTitle {
            get {
                return ResourceManager.GetString("HTTPSUncheckedWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string WebsiteTitleLabel_Text {
            get {
                return ResourceManager.GetString("WebsiteTitleLabel_Text", resourceCulture);
            }
        }
    }
}
