//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserToRoles = new HashSet<UserToRole>();
        }
    
        public int Id { get; set; }
        public int SecurityQuestionAnswerId { get; set; }
        public int UserAndPasswordId { get; set; }
        public int UserActivityId { get; set; }
        public int UserDetailsId { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserActivity UserActivity { get; set; }
        public virtual UserAndPassword UserAndPassword { get; set; }
        public virtual UserSecurityQuestionAndAnswer UserSecurityQuestionAndAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserToRole> UserToRoles { get; set; }
    }
}
