//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public int SecurityQuestionAnswerId { get; set; }
        public int UserAndPasswordId { get; set; }
        public int UserActivityId { get; set; }
        public int UserDetailsId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserActivity UserActivity { get; set; }
        public virtual UserAndPassword UserAndPassword { get; set; }
        public virtual UserSecurityQuestionAndAnswer UserSecurityQuestionAndAnswer { get; set; }
    }
}
